######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 24 09:28:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

CONFIG += debug

# Input
HEADERS += udpServer.h
FORMS += udpServer.ui
SOURCES += main.cpp udpServer.cpp
