######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 24 17:26:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += udpClient.h
FORMS += udpClient.ui
SOURCES += main.cpp udpClient.cpp
